version: '3'
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www/
      - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "8878:80"
    depends_on:
      - app
    container_name: nginx_docker_laraBlog

  app: # docker-compose exec app php artisan ..
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www
    depends_on:
      -   db
    container_name: app_docker_laraBlog


  db: # docker-compose exec db bash =>  mysql -u root -p => show databases;
    image: mysql:5.7
    restart: always
    volumes:
      -   ./tmp/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: laradocker
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8101:3306"
    container_name: db_docker_laraBlog

  npm: # docker-compose run --rm : npm run dev, before that check if you installed npm with npm install,
       #  and your package-lock.json has actual dependencies.
    image: node:14
    working_dir: /var/www/home/davlatuser/LaravelDavlatBlog # make sure your path is right, in ubuntu you can type pwd for this.
    entrypoint: [ "npm" ]
    volumes:
      - "./:/var/www/home/davlatuser/LaravelDavlatBlog"
    container_name: npm_docker_laraBlog
